#![forbid(unsafe_code)]

use std::{
    env,
    error::Error,
    fs,
    path::{Path, PathBuf},
};

use quote::quote;
use schemars::schema::RootSchema;
use typify::{TypeSpace, TypeSpaceSettings};

fn main() -> Result<(), Box<dyn Error>> {
    let mut arguments = env::args_os().skip(1);
    let schema_path = arguments
        .next()
        .map(PathBuf::from)
        .ok_or("usage: contract-gen <bundled-schema> <output-file>")?;
    let output_path = arguments
        .next()
        .map(PathBuf::from)
        .ok_or("usage: contract-gen <bundled-schema> <output-file>")?;

    if arguments.next().is_some() {
        return Err("contract-gen accepts exactly two arguments".into());
    }

    generate(&schema_path, &output_path)
}

fn generate(schema_path: &Path, output_path: &Path) -> Result<(), Box<dyn Error>> {
    let schema: RootSchema = serde_json::from_slice(&fs::read(schema_path)?)?;
    let mut type_space = TypeSpace::new(&TypeSpaceSettings::default());
    type_space.add_root_schema(schema)?;

    let generated = quote! {
        // @generated by environment-reconciler-contract-gen. Do not edit.
        #![allow(clippy::all, clippy::pedantic)]

        #type_space
    };
    let syntax = syn::parse2::<syn::File>(generated)?;
    let formatted = prettyplease::unparse(&syntax);

    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output_path, formatted)?;

    Ok(())
}
